### ISSUE TITLE
Build failure on arm FreeBSD

### ISSUE THREAD

**Issue by clausecker** [go-piv/piv-go#104]
The build fails as follows on arm FreeBSD:

```
# github.com/go-piv/piv-go/piv
vendor/github.com/go-piv/piv-go/piv/pcsc_freebsd.go:29:15: 0x8010002E (untyped int constant 2148532270) overflows int32
golang.org/x/crypto/ssh/agent
*** Error code 2
```

Please check and possible add a cast to make the number negative.

**Comment by ericchiang** [comment]
I don't have access to a FreeBSD environment so I'm not able to test any changes. If someone who does have one wants to send a PR and run the tests locally, I'm happy to review

**Comment by clausecker** [comment]
Sure, let me prepare something for you.
