### ISSUE TITLE
Possibility of cutting a new release to include OpenBSD support?

### ISSUE THREAD

**Issue by qbit** [go-piv/piv-go#105]
Hi, in PR #101 support for OpenBSD was added. I made this change in preparation for https://github.com/smallstep/certificates/pull/990 , would it be possible to get a new piv-go tag cut to include this?

As noted here, upstream would prefer to use the non-auto-gen'd tag: https://github.com/smallstep/certificates/pull/990#discussion_r937223370 .

Thanks!

**Comment by ericchiang** [comment]
Thanks for opening the issue. Will do this today!

It looks like our CI is failing to find golint at HEAD, so let me fix that too before cutting the release.

**Comment by ericchiang** [comment]
Tagged https://github.com/go-piv/piv-go/releases/tag/v1.10.0

**Comment by qbit** [comment]
yay! thank you!
