### ISSUE TITLE
Expose keyRSA and keyEd25519 type

### ISSUE THREAD

**Issue by looCiprian** [go-piv/piv-go#112]
Hi!
I think that `keyRSA` and `keyEd25519` type should be exposed otherwise golang is not able to use purpose-specific interfaces such as Signer and Decrypter of that type.

For example:
``` go
priv, err := yk.PrivateKey(...)  // using a RSA pub key

// cannot cast to *piv.keyRSA like: "priv.(*piv.keyRSA)" since the type is not exposed

priv.Decrypt(....) // will not work, golang is not able to convert crypto.PrivateKey, to piv.keyRSA since is not exposed
```

Let me know if I am wrong, thanks!

**Comment by ericchiang** [comment]
Hey! With crypto.PrivateKey, you're generally expected to type cast for signing and decryption:
- https://pkg.go.dev/crypto#Decrypter
- https://pkg.go.dev/crypto#PrivateKey
- https://pkg.go.dev/crypto#Signer

So something like:

```
priv, err := yk.PrivateKey(...)
if err != nil {
    // ...
}
decrypter, ok := priv.(crypto.Decrypter)
if !ok {
    // ...
}
decrypter.Decrypt(...)
```

Going to close out since that seems like it answers your question

**Comment by looCiprian** [comment]
Many thanks!
