### ISSUE TITLE
Support for linux armv7

### ISSUE THREAD

**Issue by leejack1000** [go-piv/piv-go#114]
I want to build this project to linux armv7 device
cmd: env GOOS=linux GOARCH=arm GOARM=7 go build
got errors:
  .../github.com/go-piv/piv-go@v1.10.0/piv/piv.go:103:7: undefined: scContext
  .../github.com/go-piv/piv-go@v1.10.0/piv/piv.go:104:7: undefined: scHandle
  .../github.com/go-piv/piv-go@v1.10.0/piv/piv.go:105:7: undefined: scTx
  .../github.com/go-piv/piv-go@v1.10.0/piv/key.go:521:19: undefined: scTx
  .../github.com/go-piv/piv-go@v1.10.0/piv/key.go:614:29: undefined: scTx
  .../github.com/go-piv/piv-go@v1.10.0/piv/key.go:668:24: undefined: scTx
  .../github.com/go-piv/piv-go@v1.10.0/piv/key.go:773:59: undefined: scTx
  .../github.com/go-piv/piv-go@v1.10.0/piv/key.go:929:22: undefined: scTx
  .../github.com/go-piv/piv-go@v1.10.0/piv/key.go:1085:22: undefined: scTx
  .../github.com/go-piv/piv-go@v1.10.0/piv/key.go:1130:24: undefined: scTx
  .../github.com/go-piv/piv-go@v1.10.0/piv/key.go:1130:24: too many errors

**Comment by ericchiang** [comment]
You'd have to add a build tag to one of the pcsc_*.go files, and potentially fix some of the cgo declarations https://github.com/go-piv/piv-go/tree/master/piv

I don't have an arm7 device to test, so I haven't added the tags. Feel free to send a PR!

**Comment by leejack1000** [comment]
Just use the cmd(env GOOS=linux GOARCH=arm GOARM=7 go build) to build, you will get the errors.
Don't need to have device first.(Maybe can use docker)
Can you fix the compiler problem first?

**Comment by circa10a** [comment]
If anyone else comes across this issue, here is how I was able to build for linux arm in CI on debian 11:

```bash
apt-get update && apt-get install -y gcc gcc-aarch64-linux-gnu pkg-config pcscd pcsc-tools libpcsclite-dev
# For linux arm64 builds, we need the arm64 libs for the aarch64 gcc compiler
dpkg --add-architecture arm64 && apt-get update && apt-get install -y --no-install-recommends libpcsclite-dev:arm64

**Comment by leejack1000** [comment]
Good, thanks
