### ISSUE TITLE
Bump go.mod version

### ISSUE THREAD

**Issue by udf2457** [go-piv/piv-go#120]
Could I prompt you to bump the go.mod version, it's currently `1.16`.

Per the [Go release policy,](https://go.dev/doc/devel/release) they only support two prior major releases.

Also this is not just a cosmetic issue, per the [gomod-ref ](https://go.dev/doc/modules/gomod-ref), this value affects (a) use of new language features (b) behaviour of go command.  Bumping the go.mod version has a positive effect on both.

**Comment by ericchiang** [comment]
Closing per: https://github.com/go-piv/piv-go/pull/121#issuecomment-1753880490
