### ISSUE TITLE
PIV Emulation?

### ISSUE THREAD

**Issue by idcmp** [go-piv/piv-go#125]
Hey! This library is super handy and works great with my personal key and what I'm trying to get done -- thank you!

I was wondering if there are software PIV emulators out there that I can use for testing though (preferably Linux, but could be mac if needed)?

**Comment by ericchiang** [comment]
Not that I know of, sorry (though googling turned up some results). This package, for example, tests against real hardware.

**Comment by idcmp** [comment]
No worries, I might just buy an extra key for testing then -- thanks!
