### ISSUE TITLE
Release v2

### ISSUE THREAD

**Issue by ericchiang** [go-piv/piv-go#153]
v2 introduced some breaking changes to the API, so we need to tag a new major version.

Before doing so, I want to make sure that there are no additional API changes that are needed before doing that. Currently the only change is `[24]byte` to `[]byte`. Are we sure we don't need anything else?

/cc @Quantu @joelferrier

**Comment by Quantu** [comment]
This should be the only breaking change needed as far as I know. I have been using this myself for about a week now with v4.x, v5.4, and v5.7 yubikeys without issue. I do have a little new functionality I want to add that I'll have PRs for soon, but it doesn't affect current API calls.

**Comment by 84adam** [comment]
Any updates you can provide on this? Thank you!

**Comment by ericchiang** [comment]
Apologies for the delay here everyone. Life's been extremely busy

Thanks for the feedback that this is working! I've gone ahead and tagged v2.0.0 and promoted the v2 branch to default. I think that should fix this

**Comment by 84adam** [comment]
Thank you!
