### ISSUE TITLE
Slot* variables using wrong Object IDs?

### ISSUE THREAD

**Issue by dnesting** [go-piv/piv-go#29]
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-73-4.pdf#page=30 (in agreement with https://developers.yubico.com/PIV/Introduction/Certificate_slots.html) says:
| Purpose | Key Reference | BER-TLV Tag |
| --- | --- | --- |
| PIV Authentication | `9A` | `5FC105` |
| Digital Signature | `9C` | `5FC10A` |
| Key Management | `9D` | `5FC10B` |
| Card Authentication | `9E` | `5FC101` |

https://github.com/go-piv/piv-go/blob/4cd4b281ef64d92293e9522bcc508730df310dd8/piv/key.go#L224-L226

| Purpose | Slot | Tag | |
| --- | --- | --- | --- |
| SlotAuthentication | `0x9a` | **`0x5fc101`** | seems to be using object for card auth? |
| SlotSignature | `0x9c` | `0x5fc10a` | ok |
| SlotCardAuthentication | `0x9e` | **`0x5fc10b`** | seems to be using object for key management? |

When inspecting the card through `pkcs11-tool` it does look like the wrong slots are being manipulated.

Also should there be a variable for the Key Management slot?

**Comment by ericchiang** [comment]
Woops, yep you're right. Sent #30

**Comment by ericchiang** [comment]
This has been tagged https://github.com/go-piv/piv-go/releases/tag/v1.2.0
