### ISSUE TITLE
PIN is not obtained for second signature with "always" PIN policy

### ISSUE THREAD

**Issue by FiloSottile** [go-piv/piv-go#49]
Got this report downstream, looks like piv-go is not obtaining and passing the PIN for the subsequent signature operations when the policy is ALWAYS.

FiloSottile/yubikey-agent#6

**Comment by ericchiang** [comment]
@joneskoo would you mind taking a look at #50?

**Comment by joneskoo** [comment]
I’ll try to remember to test this later… I was just playing around with the yubikey-agent and discovered this by chance so this was more a curiosity than blocker for me but I figured better report it still.

So many thanks for you all doing this, I’ve been thinking the problem solved by yubikey-agent too and it’s just a perfect solution.

**Comment by joneskoo** [comment]
@ericchiang I just realize, looking the code you’re parsing the attestation certificate. It would’t work for the imported key in my example?

Maybe this would need an additonal PIN policy hint or retry with PIN, or just acknowledge it’s not supported on 9a and add the pin policy for slots that have it by default?

**Comment by ericchiang** [comment]
@joneskoo thanks for the follow up info! Opened #52
