### ISSUE TITLE
YubiKey 5Ci form factor

### ISSUE THREAD

**Issue by xoebus** [go-piv/piv-go#62]
I'm using the piv-go library via [yubikey-agent](https://github.com/FiloSottile/yubikey-agent) with a [YubiKey 5Ci](https://www.yubico.com/product/yubikey-5ci). I was getting errors when trying to sign which looked like:

```
agent 13: failed to prepare private key: parse attestation cert: parsing extension: unrecognized formfactor: 0x5
```

I patched the library with the following patch and everything seems to work as expected now.

``` patch
diff --git a/piv/key.go b/piv/key.go
index f8679b1..fc1eff3 100644
--- a/piv/key.go
+++ b/piv/key.go
@@ -66,6 +66,7 @@ const (
 	FormfactorUSBANano
 	FormfactorUSBCKeychain
 	FormfactorUSBCNano
+	FormfactorUSBCLightning
 )
 
 // Attestation returns additional information about a key attested to be on a
@@ -142,6 +143,8 @@ func (a *Attestation) addExt(e pkix.Extension) error {
 			a.Formfactor = FormfactorUSBCKeychain
 		case 0x04:
 			a.Formfactor = FormfactorUSBCNano
+		case 0x05:
+			a.Formfactor = FormfactorUSBCLightning
 		default:
 			return fmt.Errorf("unrecognized formfactor: 0x%x", e.Value[0])
 		}
```

Would you accept a pull request to add this form factor to the library?

Thanks!

**Comment by ericchiang** [comment]
Yeah feel free to send it :)

**Comment by grempe** [comment]
A new release of `piv-go` that incorporates this fix, that could be pulled into `yubikey-agent` would be helpful I think.

https://github.com/FiloSottile/yubikey-agent/issues/34
