### ISSUE TITLE
Cross compiling for ARM

### ISSUE THREAD

**Issue by bryfry** [go-piv/piv-go#71]
I get the below error when trying to build the piv-go project to run on arm.  Apologies if I am simply missing a dependency.

```
ubuntu@tmc:~/go/src/github.com/filosottile/yubikey-agent$ GOOS=linux GOARCH=arm GOARM=5 go build 
# github.com/go-piv/piv-go/piv
../../../../pkg/mod/github.com/go-piv/piv-go@v1.5.0/piv/piv.go:100:7: undefined: scContext
../../../../pkg/mod/github.com/go-piv/piv-go@v1.5.0/piv/piv.go:101:7: undefined: scHandle
../../../../pkg/mod/github.com/go-piv/piv-go@v1.5.0/piv/piv.go:102:7: undefined: scTx

ubuntu@tmc:~/go/pkg/mod/github.com/go-piv/piv-go@v1.5.0/piv$ GOOS=linux GOARCH=arm GOARM=5 go build
# github.com/go-piv/piv-go/piv
./piv.go:100:7: undefined: scContext
./piv.go:101:7: undefined: scHandle
./piv.go:102:7: undefined: scTx
```

**Comment by ericchiang** [comment]
There are OS specific files that need to be added for this package to work for ARM. See the FreeBSD PR: https://github.com/go-piv/piv-go/pull/70

**Comment by Ghaith0101** [comment]
i had the same problem, so i try to compile it on arm alpine and i got the following error
`/go/pkg/mod/github.com/go-piv/piv-go@v1.5.0/piv/pcsc_linux.go:29:12: constant 2148532270 overflows _Ctype_long`

**Comment by philandstuff** [comment]
@Ghaith0101  that sounds like the same error reported in #76

**Comment by Ghaith0101** [comment]
actually it is exactlly what you descripe in #76 i allready forked the repo and currently i am testing it if it will work with windows and os, then i will make a merge request

**Comment by ostaebler** [comment]
@Ghaith0101 Any news on the PR? I'm running in the same issue...

**Comment by Ghaith0101** [comment]
@ostaebler ishould be done with it this weekend, sorry for being late

**Comment by Ghaith0101** [comment]
#81

**Comment by flokli** [comment]
This should be fixed by https://github.com/go-piv/piv-go/pull/81, shouldn't it?

**Comment by Ghaith0101** [comment]
Yes i tested ist under
```
FROM i386/golang:1.15.2-buster
FROM arm32v7/golang:1.15.2-buster
```
and it built
