### ISSUE TITLE
RSA stored with OpenPGP

### ISSUE THREAD

**Issue by tcastelly** [go-piv/piv-go#86]
Hello,

Thank you very much for this project. 
On my Yubikey I [imported RSA keys](https://support.yubico.com/hc/en-us/articles/360013790259-Using-Your-YubiKey-with-OpenPGP) to be able to sign/encrypt/authenticate. I use OpenPGP for this. I'm wondering if I can use this project to do the same.

My `PublicKeyAlgorithm` is `ECDSA`, so I guess it's the "internal" certificat of my Yubikey not my imported keys.

Thanks.

**Comment by ericchiang** [comment]
My understanding is that PIV applet and the GPG applet are separate on Yubikeys, and that you can't important keys generated in one through another.

https://support.yubico.com/hc/en-us/articles/360013645480-Resetting-the-Smart-Card-PIV-Applet-on-Your-YubiKey

https://support.yubico.com/hc/en-us/articles/360013761339-Resetting-the-OpenPGP-Applet-on-the-YubiKey
