### ISSUE TITLE
Cross-compiling requirements

### ISSUE THREAD

**Issue by hazcod** [go-piv/piv-go#94]
Hi!

Curious what packages I'd need (next to ` libpcsclite-dev`) for cross-compiling?

```
Error: ../../pkg/ui/open_linux.go:4:9: undefined: exec
66
# github.com/go-piv/piv-go/piv
67
Error: /home/runner/go/pkg/mod/github.com/go-piv/piv-go@v1.8.0/piv/key.go:448:19: undefined: scTx
68
Error: /home/runner/go/pkg/mod/github.com/go-piv/piv-go@v1.8.0/piv/key.go:541:29: undefined: scTx
69
Error: /home/runner/go/pkg/mod/github.com/go-piv/piv-go@v1.8.0/piv/key.go:595:24: undefined: scTx
70
Error: /home/runner/go/pkg/mod/github.com/go-piv/piv-go@v1.8.0/piv/key.go:708:59: undefined: scTx
71
Error: /home/runner/go/pkg/mod/github.com/go-piv/piv-go@v1.8.0/piv/key.go:864:22: undefined: scTx
72
Error: /home/runner/go/pkg/mod/github.com/go-piv/piv-go@v1.8.0/piv/key.go:1020:22: undefined: scTx
73
Error: /home/runner/go/pkg/mod/github.com/go-piv/piv-go@v1.8.0/piv/key.go:1065:24: undefined: scTx
74
Error: /home/runner/go/pkg/mod/github.com/go-piv/piv-go@v1.8.0/piv/piv.go:103:7: undefined: scContext
75
Error: /home/runner/go/pkg/mod/github.com/go-piv/piv-go@v1.8.0/piv/piv.go:104:7: undefined: scHandle
76
Error: /home/runner/go/pkg/mod/github.com/go-piv/piv-go@v1.8.0/piv/piv.go:105:7: undefined: scTx
77
Error: /home/runner/go/pkg/mod/github.com/go-piv/piv-go@v1.8.0/piv/key.go:1065:24: too many errors
78

```

**Comment by ericchiang** [comment]
Since this library uses cgo, you'll have to follow those instructions https://pkg.go.dev/cmd/cgo

> When cross-compiling, you must specify a C cross-compiler for cgo to use. You can do this by setting the generic CC_FOR_TARGET or the more specific CC_FOR_${GOOS}_${GOARCH} (for example, CC_FOR_linux_arm) environment variable when building the toolchain using make.bash, or you can set the CC environment variable any time you run the go tool.

It also depends on what platform you're cross compiling for. This package only supports a handful of architectures

https://github.com/go-piv/piv-go/tree/master/piv

Going to close since this seems like a general question about cross compiling cgo. Please reopen if there's anything wrong with our build tags or something like that.

**Comment by hazcod** [comment]
I think at one point It'd be nice to have build instructions for cross-compiling this library.
