### ISSUE TITLE
Windows: the Smart card resource manager is not running

### ISSUE THREAD

**Issue by hazcod** [go-piv/piv-go#96]
Hi! Trying to get a go-piv client working on Windows.
I've started  'smart card' in services.msc, however a call to `GetCards()` will always error with `connecting to pscs: the Smart card resource manager is not running`.

Any idea?

**Comment by ericchiang** [comment]
There's a couple suggestions in the install section about additional software that may help https://github.com/go-piv/piv-go#installation

But unfortunately I don't have a windows machine to test this on, so I don't know.

**Comment by hazcod** [comment]
@tobiaskohlbau any idea? I installed the yubikey minidriver, rebooted and manually started both SmartCard services.

**Comment by tobiaskohlbau** [comment]
> @tobiaskohlbau any idea? I installed the yubikey minidriver, rebooted and manually started both SmartCard services.

Unfortunately not. I've never encountered such error nor did I need to start the service manually. Maybe it's an access rights issue? I've ran this under an administration account.

If you could share your code and setup I could possibly try this on my machine and key.

**Comment by hazcod** [comment]
In the end this seemed to only occur on a virtual machine where I tried to use Windows Hello, so will close for now.  Thanks all!
