### ISSUE TITLE
Go PIV do not give Shared access to multiple processes

### ISSUE THREAD

**Issue by brhaspat** [go-piv/piv-go#99]
https://github.com/go-piv/piv-go/blob/4b80d66ae5adc073df66163a14343939848fd742/piv/pcsc_unix.go#L97

Multiple processes cannot acquire YubiKey if I am using go-piv.

but if we pass ```C.SCARD_SHARE_SHARED```  in place of ```C.SCARD_SHARE_EXCLUSIVE```

this will solve the problem without any side effects.

**Comment by ericchiang** [comment]
Dupe of https://github.com/go-piv/piv-go/issues/47#issuecomment-903355147 ?
